 var parent = {
        son1:function(){
            $(".headskin1").removeClass("hi");
            $(".headskin1").addClass("vi");
        },
        son2:function(){
            $(".headskin2").removeClass("hi");
            $(".headskin2").addClass("vi");
        },
        son202:function(){
            $(".headskin2").removeClass("vi");
            $(".headskin2").addClass("hi");
        },
        son3:function(){
            $(".skinfoot").removeClass("hi");
            $(".skinfoot").addClass("vi");
        },
        son4:function(){
            $(".headsample").removeClass("hi");
            $(".headsample").addClass("vi mar1");
        },
        son5:function(){
            $(".headskin").removeClass("head02");
            $(".headskin").addClass("head01");
        },
        son6:function(){
            $(".headskin2b").removeClass("hi");
            $(".headskin2b").addClass("vi");
        },
        son606:function(){
            $(".headskin2b").removeClass("vi");
            $(".headskin2b").addClass("hi");
        },
        son7:function(){
            $(".headskin2a").removeClass("hi");
            $(".headskin2a").addClass("vi");
        },
        son707:function(){
            $(".headskin2a").removeClass("vi");
            $(".headskin2a").addClass("hi");
        },
        son8:function(){
            $(".headsample").removeClass("mar1");
            $(".headsample").addClass("mar2");
        },
        son9:function(){
            $(".headskin3").removeClass("hi");
            $(".headskin3").addClass("vi");
        },
        son909:function(){
            $(".headskin3").removeClass("vi");
            $(".headskin3").addClass("hi");
        },
        son10:function(){
            $(".skinfoot").removeClass("hi");
            $(".skinfoot").addClass("vi");
        },
        son10010:function(){
            $(".skinfoot").removeClass("vi");
            $(".skinfoot").addClass("hi");
        },
        son11:function(){
            $(".headsample").removeClass("mar2");
            $(".headsample").addClass("mar1");
        },
        son11011:function(){
            $(".headsample").removeClass("mar1");
            $(".headsample").addClass("mar2");
        },
        son12:function(){
            $(".headskin3head").removeClass("hi");
            $(".headskin3head").addClass("vi");
        },
        son12012:function(){
            $(".headskin3head").removeClass("vi");
            $(".headskin3head").addClass("hi");
        },
        son13:function(){
            $(".headskin").removeClass("headskinhei2");
            $(".headskin").addClass("headskinhei1");
        },
        son13013:function(){
            $(".headskin").removeClass("headskinhei1");
            $(".headskin").addClass("headskinhei2");
        },
        son14:function(){
            $(".autoskin").removeClass("hi");
            $(".autoskin").addClass("vi");
        },
        son14014:function(){
            $(".autoskin").removeClass("vi");
            $(".autoskin").addClass("hi");
        },
        son15:function(){
            $(".headskin1-1").removeClass("bgc2");
            $(".headskin1-1").addClass("bgc1");
        },
        son15015:function(){
            $(".headskin1-1").removeClass("bgc1");
            $(".headskin1-1").addClass("bgc2");
        },
        son16:function(){
            $(".headskin1-2").removeClass("bgc1");
            $(".headskin1-2").addClass("bgc2");
        },      
        son16016:function(){
            $(".headskin1-2").removeClass("bgc2");
            $(".headskin1-2").addClass("bgc1");
        },
        son17:function(){
            $(".headskin1-3").removeClass("bgc1");
            $(".headskin1-3").addClass("bgc2");
        },
        son18:function(){
            $(".headskin1-4").removeClass("bgc1");
            $(".headskin1-4").addClass("bgc2");
        },
        son19:function(){
            $(".headskin1-5").removeClass("bgc1");
            $(".headskin1-5").addClass("bgc2");
        },
        son20:function(){
            $(".headskin1-6").removeClass("bgc1");
            $(".headskin1-6").addClass("bgc2");
        },
        son21:function(){
            $(".headskin1-7").removeClass("bgc1");
            $(".headskin1-7").addClass("bgc2");
        },
        son22:function(){
            $(".headskin1-8").removeClass("bgc1");
            $(".headskin1-8").addClass("bgc2");
        },
        son23:function(){
            $(".headskin1-9").removeClass("bgc1");
            $(".headskin1-9").addClass("bgc2");
        },
        son24:function(){
            $(".headskin1-10").removeClass("bgc1");
            $(".headskin1-10").addClass("bgc2");
        },
        son:function(){

        },
        son:function(){

        },
        son:function(){

        },
    }